<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Aemeath.Speech</RootNamespace>
    <AssemblyName>Aemeath.Speech</AssemblyName>
    <UseRidGraph>true</UseRidGraph>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Porcupine" />
    <PackageReference Include="Whisper.net" />
    <PackageReference Include="Whisper.net.Runtime" />
    <PackageReference Include="NAudio" />
    <PackageReference Include="Microsoft.Windows.SDK.NET" />
  </ItemGroup>

</Project>
