<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Aemeath.Pet</RootNamespace>
    <AssemblyName>Aemeath.Pet</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="SixLabors.ImageSharp" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aemeath.Core\Aemeath.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="..\..\assets\animations\pet\daiji.gif">
      <Link>Assets\animations\pet\daiji.gif</Link>
    </AvaloniaResource>
    <AvaloniaResource Include="..\..\assets\animations\pet\yidong.gif">
      <Link>Assets\animations\pet\yidong.gif</Link>
    </AvaloniaResource>
    <AvaloniaResource Include="..\..\assets\animations\pet\dianji.gif">
      <Link>Assets\animations\pet\dianji.gif</Link>
    </AvaloniaResource>
    <AvaloniaResource Include="..\..\assets\animations\pet\aemeath-mini-failed.gif">
      <Link>Assets\animations\pet\aemeath-mini-failed.gif</Link>
    </AvaloniaResource>
    <AvaloniaResource Include="..\..\assets\animations\pet\aemeath-mini-jumping.gif">
      <Link>Assets\animations\pet\aemeath-mini-jumping.gif</Link>
    </AvaloniaResource>
    <AvaloniaResource Include="..\..\assets\animations\pet\aemeath-mini-review.gif">
      <Link>Assets\animations\pet\aemeath-mini-review.gif</Link>
    </AvaloniaResource>
    <AvaloniaResource Include="..\..\assets\animations\pet\aemeath-mini-running-left.gif">
      <Link>Assets\animations\pet\aemeath-mini-running-left.gif</Link>
    </AvaloniaResource>
    <AvaloniaResource Include="..\..\assets\animations\pet\aemeath-mini-waiting.gif">
      <Link>Assets\animations\pet\aemeath-mini-waiting.gif</Link>
    </AvaloniaResource>
    <AvaloniaResource Include="..\..\assets\animations\pet\aemeath-mini-waving.gif">
      <Link>Assets\animations\pet\aemeath-mini-waving.gif</Link>
    </AvaloniaResource>
  </ItemGroup>

</Project>
